{:user {:plugins [[cider/cider-nrepl "0.16.0"]
                  ;[refactor-nrepl "2.3.1"]
                  [lein-ancient "0.6.15"]
                  [jonase/eastwood "0.2.5"]
                  [lein-simpleton "1.3.0"]
                  [lein-kibit "0.1.6"]
                  [lein-codox "0.10.3"]
                  [lein2-eclipse "2.0.0"]
                  [hiccup-bridge "1.0.1"]
                  [lein-marginalia "0.9.1"]
                  [lein-set-version "0.4.1"]
                  [lein-create-template "0.2.0"]]
        :dependencies [[slamhound "1.5.5"]
                       [datawalk "0.1.10"]
                       ;[org.clojure/clojure "1.9.0-alpha14"]
                       ]
        :aliases {"slamhound" ["run" "-m" "slam.hound"]}}}
